### PR TITLE
update lspatch

### PR DESCRIPTION
**Pull request by janisslsm**
fixes A14 QPR2 and android 15 crashing. uses https://github.com/janisslsm/LSPatch

### CODE REVIEW

**Comment by janisslsm** [comment]
noticed a issue with it not being able to find hookMethod, will look into it.

**Comment by wingio** [comment]
> noticed a issue with it not being able to find hookMethod, will look into it. Might be related to the LSPosed new/old api stuff.

alright just let me know when you fix that

**Comment by janisslsm** [comment]
@wingio fixed it. tested on A14 february patch and A15 DP1, works fine.

**Comment by wingio** [comment]
> @wingio fixed it. tested on A14 february patch (not QPR2, on my phone) and A15 DP1 (emulator), everything loads fine including vendetta.

alright ill review it tomorrow

**Review by wingio — APPROVED** [review]

**Pull request merged**
